
f = open('abc.txt','r')
print('file name',f.name)
print('file mode',f.mode)
print('is file closed',f.closed)
print('is file readable',f.readable())
print('is file writable',f.writable())
f.close()
print('is file closed',f.closed)

print('-------------------------- default mode ------------------------------------')
f = open('abc.txt')
print('file name',f.name)
print('file mode',f.mode)
print('is file closed',f.closed)
print('is file readable',f.readable())
print('is file writable',f.writable())
f.close()
print('is file closed',f.closed)
